SET TERMOUT ON;
SET SERVEROUTPUT ON;
SET ERRORLOGGING ON;
SET AUTOPRINT ON;
SET ECHO ON;
SET HEADING ON;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
--WHENEVER SQLERROR CONTINUE NONE;

SET HEADING OFF;
SELECT 'SELECT * FROM region_types;' FROM DUAL;
SET HEADING ON;
SELECT * FROM region_types;

SET HEADING OFF;
SELECT 'SELECT * FROM countries;' FROM DUAL;
SET HEADING ON;
SELECT * FROM countries;

SET HEADING OFF;
SELECT 'SELECT * FROM regions;' FROM DUAL;
SET HEADING ON;
SELECT * FROM regions;

SET HEADING OFF;
SELECT 'SELECT * FROM pl_regions;' FROM DUAL;
SET HEADING ON;
SELECT * FROM pl_regions;

SET HEADING OFF;
SELECT 'SELECT * FROM addresses;' FROM DUAL;
SET HEADING ON;
SELECT * FROM addresses;

SET HEADING OFF;
SELECT 'SELECT * FROM persons;' FROM DUAL;
SET HEADING ON;
SELECT * FROM persons;

SET HEADING OFF;
SELECT 'SELECT * FROM economic_sectors;' FROM DUAL;
SET HEADING ON;
SELECT * FROM economic_sectors;

SET HEADING OFF;
SELECT 'SELECT * FROM organizations;' FROM DUAL;
SET HEADING ON;
SELECT * FROM organizations;

SET HEADING OFF;
SELECT 'SELECT * FROM employees;' FROM DUAL;
SET HEADING ON;
SELECT * FROM employees;

SET HEADING OFF;
SELECT 'SELECT * FROM customers;' FROM DUAL;
SET HEADING ON;
SELECT * FROM customers;

SET TERMOUT OFF;
SET SERVEROUTPUT OFF;
SET ERRORLOGGING OFF;
SET AUTOPRINT OFF;
SET ECHO OFF;
SET HEADING OFF;