SET TERMOUT ON;
SET SERVEROUTPUT ON;
SET ERRORLOGGING ON;
SET AUTOPRINT ON;
SET ECHO ON;
SET HEADING ON;

WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER=ecommerce;

DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE organization_addresses CASCADE CONSTRAINTS;
DROP TABLE organizations CASCADE CONSTRAINTS;
DROP TABLE economic_sectors CASCADE CONSTRAINTS;
DROP TABLE person_addresses CASCADE CONSTRAINTS;
DROP TABLE persons CASCADE CONSTRAINTS;
DROP TABLE addresses CASCADE CONSTRAINTS;
DROP TABLE pl_regions CASCADE CONSTRAINTS;
DROP TABLE regions CASCADE CONSTRAINTS;
DROP TABLE region_types CASCADE CONSTRAINTS;
DROP TABLE countries CASCADE CONSTRAINTS;

COMMIT;

SET TERMOUT OFF;
SET SERVEROUTPUT OFF;
SET ERRORLOGGING OFF;
SET AUTOPRINT OFF;
SET ECHO OFF;
SET HEADING OFF;